{
  "blank_issues_enabled": false,
  "contact_links": [
	{
	  "name": "GitLens Discussions",
	  "url": "https://github.com/gitkraken/vscode-gitlens/discussions",
	  "about": "Ask questions and discuss with other GitLens users"
	}
  ]
}

